### ISSUE TITLE
March 19th session 'TODO' summaries

### ISSUE THREAD

**Issue by jackharrhy** [djkean/FoodForAll#24]
# fleshed out action system

first thing to tackle would def. be finishing off what i started with the more fleshed out 'action' system

similar to what i did for the battle event:

![image](https://user-images.githubusercontent.com/6486417/159569528-5bb8fde7-0e5a-4e75-b32c-87386c12af57.png)

(added lines 308 & 309, one for creation the 'action', and the next for rendering said action)

![image](https://user-images.githubusercontent.com/6486417/159569729-8a3a123b-79dc-4f8b-a846-0c78736b84db.png)

308 being the invocation of a function that returns a nice object that represents an 'action'

![image](https://user-images.githubusercontent.com/6486417/159569892-6bb994a7-c92d-4180-8ec2-df58ef46d845.png)

309 being the invocation of the renderAction function, which contains a big switch-case statement, and what i did is hit the one that renders the 'battle' case

---

you should:

first tackle the 'health action'

![image](https://user-images.githubusercontent.com/6486417/159570071-6ceeb775-cfcc-4bd0-966f-c7bf169a11b9.png)

- [x] by filling out this function

![image](https://user-images.githubusercontent.com/6486417/159570118-9a3d9771-0ad2-4b8f-a5b7-0f929819ce2a.png)

- [x] and then define how this function renders (you can steal a _lot_ of code from the above `Battle` case, such as the: `container`, `imageContainer`, `playerImg`, `text`, so on

---

- [x] then, basically rinse-and-repeat the above steps, but for the `Injury` action as well
- [x] remove `eventText` and any reference to it from your `FFA.js` / `index.html` files, since it should then be replaced with whats going on in `renderAction`

# Don't insta-kill enemy

![image](https://user-images.githubusercontent.com/6486417/159570979-e1e127ab-09b1-47dc-a08b-3a430e203247.png)

Currently:
- a player is picked to have an event occur to them
- they can roll a 1, therefore ending up in the `if(event == 1) { ...` area
- within this area, an enemy is picked
- they do damage to eachother
- but the damage _doesn't really matter currently_, since the player is pushed back into the list of active players, with no consequence to the damage actually done

- [x] Instead:
- You should only push the players back into `playerInfo` if they have health greater than 0
- Basically, if a battle means two players do damages to one another, but both still have positive health values, they should both be put back into the pool of eligible players
- It also means there is a chance both players can die in a given round if both players health goes below 0

_This also means `createBattleAction` is incorrect_

![image](https://user-images.githubusercontent.com/6486417/159571471-4bfb4bbb-368b-4878-94a6-d13bc8f7ada4.png)

- [x] fix the `text: ...` property on createBattleAction to describe that _both_ players are fighting each other

# More complex rounds

_broken out into #25_

Once you have done the above, tackle this blob:

![image](https://user-images.githubusercontent.com/6486417/159571675-3ee8bda5-137b-47df-939f-88dfb4f96841.png)

If you've gotten this far through this issue, the above would be a good chance for you to think about how you could tackle this on your own, and if need be, you can reach out to me for some context (I would recommend trying to write it out in psuedocode first before writing it down here)

# Health UI

_broken out into #26_

_I think this one is the least important, hence it is last_

Basically the health bar system as described throughout the code

![image](https://user-images.githubusercontent.com/6486417/159571830-1b65f2b5-6ec5-4032-9b88-94fc329698f0.png)

If you need more context / help here, let me know!

Storefront reference:
- https://github.com/jackharrhy/Storefront/blob/master/storefront-frontend/src/Component/Damage.js
- https://github.com/jackharrhy/Storefront/blob/master/storefront-frontend/src/index.css
